name: ATLAS

on:
  pull_request:

jobs:
  atlas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          clean: false
          path: ${{ github.event.repository.name }}
          token: ${{ secrets.MERGE_TOKEN }}

      - name: Checkout ATLAS
        uses: actions/checkout@v4
        with:
          repository: atlas/atlas-pipeline
          ref: master
          path: atlas-pipeline
          token: ${{ secrets.MERGE_TOKEN }}

      - name: Run ATLAS
        run: |
          set -eu

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            ATLAS_TRIGGER="pr"
          else
            ATLAS_TRIGGER="push"
          fi

          WORKSPACE_ROOT="${{ github.workspace }}"
          TARGET_REPO_NAME="${{ github.event.repository.name }}"
          TARGET_REPO_ROOT="$WORKSPACE_ROOT/$TARGET_REPO_NAME"
          ATLAS_REPO_ROOT="$WORKSPACE_ROOT/atlas-pipeline"
          ATLAS_LIB="$ATLAS_REPO_ROOT/src/lib"

          if [ -n "${PYTHONPATH:-}" ]; then
            export PYTHONPATH="$ATLAS_LIB:$PYTHONPATH"
          else
            export PYTHONPATH="$ATLAS_LIB"
          fi

          REQUIRED_REPOS_FILE="$WORKSPACE_ROOT/.atlas-required-repos.tsv"
          python3 -c 'import sys; from pathlib import Path; from atlas.config import load_config; config = load_config(Path(sys.argv[1])); [print("{}\t{}".format(required_repo.repository, required_repo.ref or "")) for required_repo in config.meta.required_repos]' "$TARGET_REPO_ROOT/.atlas/pipeline.xml" > "$REQUIRED_REPOS_FILE"

          ORIGIN_URL="$(git -C "$TARGET_REPO_ROOT" remote get-url origin)"
          ORIGIN_AUTH_HEADER="$(git -C "$TARGET_REPO_ROOT" config --get-all "http.$ORIGIN_URL.extraheader" | head -n 1 || true)"
          if [ -z "$ORIGIN_AUTH_HEADER" ]; then
            ORIGIN_BASE_URL="$(python3 -c 'import sys; from urllib.parse import urlparse; parsed = urlparse(sys.argv[1]); print(f"{parsed.scheme}://{parsed.netloc}/" if parsed.scheme and parsed.netloc else "")' "$ORIGIN_URL")"
            if [ -n "$ORIGIN_BASE_URL" ]; then
              ORIGIN_AUTH_HEADER="$(git -C "$TARGET_REPO_ROOT" config --get-all "http.$ORIGIN_BASE_URL.extraheader" | head -n 1 || true)"
            fi
          fi

          if [ -s "$REQUIRED_REPOS_FILE" ]; then
            while IFS="$(printf '\t')" read -r REQUIRED_REPO REQUIRED_REF; do
              REQUIRED_REPO_NAME="${REQUIRED_REPO##*/}"
              REQUIRED_REPO_ROOT="$WORKSPACE_ROOT/$REQUIRED_REPO_NAME"

              if [ "$REQUIRED_REPO_NAME" = "$TARGET_REPO_NAME" ]; then
                echo "atlas: config error: required repository '$REQUIRED_REPO' matches target repository" >&2
                exit 2
              fi

              REQUIRED_REPO_URL="$(python3 -c 'import sys; from urllib.parse import urlparse; origin_url = sys.argv[1].strip(); required_repo = sys.argv[2].strip().strip("/"); parsed = urlparse(origin_url); host_path = origin_url[4:] if origin_url.startswith("git@") else ""; host, sep, _ = host_path.partition(":") if host_path else ("", "", ""); print(f"git@{host}:{required_repo}.git" if sep else (f"{parsed.scheme}://{parsed.netloc}/{required_repo}.git" if parsed.scheme and parsed.netloc else ""))' "$ORIGIN_URL" "$REQUIRED_REPO")"

              if [ -z "$REQUIRED_REPO_URL" ]; then
                echo "atlas: error: unable to derive clone URL for required repository '$REQUIRED_REPO'" >&2
                exit 3
              fi

              if [ -d "$REQUIRED_REPO_ROOT/.git" ]; then
                echo "ATLAS: required repository already present: $REQUIRED_REPO_NAME"
                continue
              fi

              GIT_CLONE_CMD=(git -C "$TARGET_REPO_ROOT")
              if [ -n "$ORIGIN_AUTH_HEADER" ]; then
                GIT_CLONE_CMD+=(-c "http.extraheader=$ORIGIN_AUTH_HEADER")
              fi

              if [ -n "$REQUIRED_REF" ]; then
                "${GIT_CLONE_CMD[@]}" clone --depth 1 --branch "$REQUIRED_REF" "$REQUIRED_REPO_URL" "$REQUIRED_REPO_ROOT"
              else
                "${GIT_CLONE_CMD[@]}" clone --depth 1 "$REQUIRED_REPO_URL" "$REQUIRED_REPO_ROOT"
              fi
            done < "$REQUIRED_REPOS_FILE"
          fi

          cd "$TARGET_REPO_ROOT"

          python3 -m atlas.main --repo-root "$ATLAS_REPO_ROOT" validate
          python3 -m atlas.main --repo-root "$ATLAS_REPO_ROOT" run --trigger "$ATLAS_TRIGGER"

      - name: Upload ATLAS output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: atlas-output-${{ github.run_id }}
          path: ${{ github.event.repository.name }}/bld/atlas/**
          if-no-files-found: warn
